# Generated by Django 5.1.1 on 2024-10-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('faixaetaria', models.CharField(max_length=256)),
                ('material', models.CharField(max_length=256)),
            ],
        ),
    ]
